export const ADVANCED_FORM_DEFAULTS = {
  distanceKm: "",
  durationHours: "",
  weightKg: "",
  temperatureC: "",
  terrain: "",
  packWeightKg: "",
  sweatRateLPerHour: "",
  experienceLevel: "",
  goal: "",
  hasAidStations: "",
  aidStationGapHours: "",
  distanceKmError: "",
  durationHoursError: "",
  weightKgError: "",
  temperatureCError: "",
  humidityPctError: "",
  paceMinPerKmError: "",
  terrainError: "",
  packWeightKgError: "",
  sweatRateLPerHourError: "",
  experienceLevelError: "",
  goalError: "",
  hasAidStationsError: "",
  aidStationGapHoursError: "",
};
