import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
// import getUser from "@/utils/supabase/user";
import { UserProvider } from "@/contexts/UserContext";
import Footer from "@/components/Footer";
import TermsGate from "@/components/TermsGate";
import { supabaseAdmin } from "@/utils/supabase/admin";
import getUser from "@/utils/supabase/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ultra Fueling",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  // const {
  //   data: { user },
  // } = await supabaseAdmin.auth.getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider user={user}>
          <TermsGate />
          <Navbar />
          <div className="mx-auto max-w-[1320px] px-4 py-4">
            {children}
            <Toaster position="top-right" />
          </div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
