import { Crown, Sparkles, Zap } from "lucide-react";

export const Plans = [
  {
    name: "Free Trial",
    description: "Try all premium features free",
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_MONTHLY!,
    price: 0,
    duration: "/7 days",
    features: [
      "Unlimited fueling plans",
      "Hour-by-hour breakdown",
      "Terrain + temperature adjustments",
      "AI-generated fueling notes",
      "Save plans",
      "Export plans as PDF",
    ],
    trialDays: 7,
    popular: false,
    icon: Zap,
    isTrial: true,
  },
  {
    name: "Monthly",
    description: "Best for regular training",
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_MONTHLY!,
    price: 9,
    duration: "/month",
    features: [
      "Unlimited fueling plans",
      "Hour-by-hour breakdown",
      "Terrain + temperature adjustments",
      "AI-generated fueling notes",
      "Save plans",
      "Export plans as PDF",
    ],
    popular: true,
    icon: Sparkles,
  },
  {
    name: "Yearly",
    description: "Save 27% annually",
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_YEARLY!,
    price: 79,
    duration: "/year",
    features: [
      "Unlimited fueling plans",
      "Hour-by-hour breakdown",
      "Terrain + temperature adjustments",
      "AI-generated fueling notes",
      "Save plans",
      "Export plans as PDF",
      "Save 29$ vs monthly",
    ],
    popular: false,
    icon: Crown,
  },
];
